name: library_web
description: "Практическая работа 4. Подключение REST API."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  dio: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_mock_adapter: ^0.6.1

flutter:
  uses-material-design: true